trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: VSBuild@1
  displayName: Build appservice
  inputs:
    solution: '$(Build.SourcesDirectory)/AppService/**\*.sln'
    msbuildArgs: '/p:Configuration=Debug /p:Platform="Any CPU" /p:WebPublishMethod=FileSystem /p:publishUrl="$(Build.ArtifactStagingDirectory)/build" /p:DeployOnBuild=true'
    clean: true


- task: ArchiveFiles@2
  displayName: create archive for app service deployment
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.StagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: AzureRmWebAppDeployment@4
  displayName: deploy app service
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ServiceConnectionName'
    appType: 'webApp'
    WebAppName: 'AppServiceName'
    packageForLinux: '$(Build.StagingDirectory)/**/*.zip'